// Code generated by scripts/write_build_stamp.py during `knope prepare-release`. DO NOT EDIT.

package main

// releaseVersion is the version this source tree was tagged as (no leading "v"),
// and releaseTime is when that release was prepared (RFC 3339, UTC). They exist
// so a `go install pkg@vX.Y.Z` build can report a build time: that path compiles
// this source out of the module cache and embeds no VCS metadata, so vcs.time —
// the usual fallback — is absent entirely. Baking the stamp into the released
// source is the only way to reach that build, which passes no -ldflags.
//
// The values are those of the most recently *prepared* release, so on `main`
// they lag by one release the moment work resumes — which is exactly why
// applyReleaseStamp (main.go) uses them only when the module version matches
// releaseVersion exactly. A `go install …@main` build resolves to a
// pseudo-version, doesn't match, and correctly reports no build time rather
// than the previous release's. Empty means "no stamp", never a guess: that is
// the state until the first release prepared after this file landed.
const (
	releaseVersion = "1.10.0"
	releaseTime    = "2026-09-01T01:59:59Z"
)
